# Generated by Django 5.2.1 on 2025-05-24 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id_prom', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prom', models.CharField(max_length=50)),
                ('codigo_prom', models.CharField(max_length=10)),
                ('descuento_porcentaje_prom', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio_prom', models.DateField()),
                ('fecha_fin_prom', models.DateField()),
                ('descripcion_prom', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'codigo_descuento',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(max_length=35)),
                ('telefono_hotel', models.CharField(max_length=10)),
                ('correo_hotel', models.CharField(max_length=40)),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.ciudad')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_habitacion', models.CharField(max_length=35)),
                ('capacidad_habitacion', models.CharField(max_length=3)),
                ('camas_habitacion', models.CharField(max_length=2)),
                ('descripcion_habitacion', models.CharField(max_length=400)),
                ('imagen_habitacion', models.CharField(max_length=300)),
                ('precio_habitacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_hotel', models.ForeignKey(db_column='id_hotel', on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.hotel')),
            ],
            options={
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula_cliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=25)),
                ('apellido_cliente', models.CharField(max_length=25)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('correo_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=40)),
                ('direccion_secundaria_cliente', models.CharField(blank=True, max_length=40, null=True)),
                ('ciudad_cliente', models.CharField(max_length=30)),
                ('codigo_postal_cliente', models.IntegerField()),
                ('provincia_cliente', models.CharField(max_length=50)),
                ('id_pais', models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.pais')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cedula_cliente', models.ForeignKey(db_column='cedula_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.cliente')),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.habitacion')),
                ('id_prom', models.ForeignKey(blank=True, db_column='id_prom', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.codigodescuento')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado_pago', models.CharField(max_length=15)),
                ('titular_tarjeta', models.CharField(max_length=30)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fechacaducidad_tarjeta', models.DateField()),
                ('cvv_tarjeta', models.CharField(max_length=4)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='Oro_Verde.reserva')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
