# Generated by Django 5.2.1 on 2025-05-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oro_Verde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cedula_cliente',
            field=models.ForeignKey(db_column='cedula_cliente', on_delete=django.db.models.deletion.CASCADE, to='Oro_Verde.cliente'),
        ),
    ]
